name: Physionix C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add Raspbian Repositories
      run: sudo echo -e "deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi" >> /etc/apt/sources.list
    - name: Update Repo
      run: sudo apt update
    - name: Build Physionix Application
      run: ./build.sh
